spring:
  application:
    name: SQLJudger
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/sql_judger
      password: 1122
      username: postgres
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 4
      minimum-idle: 4
      pool-name: main
  jpa:
    properties:
      hibernate:
        dialect: zunpiau.sqljudger.web.domain.PostgreSQLDialectArray
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: zunpiau.sqljudger.web.domain.PostgreSQLDialectArray
    show-sql: true
    generate-ddl: true
    database: default
  resources:
    chain:
      cache: false
    static-locations: "classpath:/dist/"
  data:
    rest:
      base-path: api
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.task.TaskExecutionAutoConfiguration
admin:
  name: admin
  password: 1234
jwt:
  header: Authorization
  secret: mySecret
  expiration: 186400
judger:
  datasources:
    - jdbc-url: jdbc:postgresql://127.0.0.1:5432/judger_test
      password: 1122
      username: postgres
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 2
      minimum-idle: 2
      pool-name: psql1

    - jdbc-url: jdbc:postgresql://127.0.0.2:5432/judger_test
      password: 1122
      username: postgres
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 2
      minimum-idle: 2
      pool-name: psql2
  task:
    exam:
      thread-name-prefix: exam-
      pool:
        max-size: 2
        core-size: 2
        queue-capacity: 10
    answersheet:
      thread-name-prefix: answerSheet-
      pool:
        max-size: 3
        core-size: 3
        queue-capacity: 100
    post:
      thread-name-prefix: post-
      pool:
        max-size: 3
        core-size: 3
        queue-capacity: 200