spring:
  application:
    name: SQLJudger
  datasource:
    hikari:
      jdbc-url:
      password:
      username:
      driver-class-name: org.postgresql.Driver
      maximum-pool-size:
      minimum-idle:
      pool-name: main
  jpa:
    properties:
      hibernate:
        dialect: zunpiau.sqljudger.web.domain.PostgreSQLDialectArray
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: zunpiau.sqljudger.web.domain.PostgreSQLDialectArray
    show-sql: true
    generate-ddl: true
    database: default
  resources:
    chain:
      cache: false
    static-locations: "classpath:/dist/"
  data:
    rest:
      base-path: api
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.task.TaskExecutionAutoConfiguration
  profiles:
    active: prod
admin:
  name:
  password:
jwt:
  header:
  secret:
  expiration:
judger:
  datasources:
    - jdbc-url:
      password:
      username:
      driver-class-name: org.postgresql.Driver
      maximum-pool-size:
      minimum-idle:
      pool-name:
  task:
    exam:
      thread-name-prefix:
      pool:
        max-size:
        core-size:
        queue-capacity:
    answersheet:
      thread-name-prefix:
      pool:
        max-size:
        core-size:
        queue-capacity:
    post:
      thread-name-prefix:
      pool:
        max-size:
        core-size:
        queue-capacity: