spring:
  application:
    name: SQLJudger
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/sql_judger
      password: 1122
      username: postgres
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 2
      pool-name: main
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    generate-ddl: true
    database: default
  resources:
    chain:
      cache: false
  data:
    rest:
      base-path: api
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.task.TaskExecutionAutoConfiguration
admin:
  name: admin
  password: 1234
jwt:
  header: Authorization
  secret: mySecret
  expiration: 86400
judger:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/judger_test
      password: 1122
      username: postgres
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 2
      pool-name: judger
  task:
    exam:
      thread-name-prefix: exam-
      pool:
        max-size: ${judger.datasource.hikari.maximum-pool-size}
        core-size: ${judger.datasource.hikari.maximum-pool-size}
        queue-capacity: 10
    answersheet:
      thread-name-prefix: answerSheet-
      pool:
        max-size: ${judger.datasource.hikari.maximum-pool-size}
        core-size: ${judger.datasource.hikari.maximum-pool-size}
        queue-capacity: 100
    post:
      thread-name-prefix: post-
      pool:
        max-size: ${judger.datasource.hikari.maximum-pool-size}
        core-size: ${judger.datasource.hikari.maximum-pool-size}
        queue-capacity: 200