spring:
  application:
    name: SQLJudger
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/sql_judger
    password: 1122
    username: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    generate-ddl: true
    database: default
  resources:
    chain:
      cache: false
  data:
    rest:
      base-path: api
admin:
  name: admin
  password: 1234
jwt:
  header: Authorization
  secret: mySecret
  expiration: 86400
judger:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/judger_test
    password: 1122
    username: postgres
    driver-class-name: org.postgresql.Driver